QUESTION_ZERO = "DID YOU SETUP ALL DEPENDENCIES AND PUT YOUR PROJECT TO THE APPROPRIATE PLACE?\
        HINT: the project root should be in the same level as this main.py. If you skip or mistake\
        this step, the following steps may not work. Please confirm (Y/N)"

QUESTION_ONE = "What is your context of this project? Usually, We expect to have a short \
        description of the project, and the main goal you want to achieve. \
            Please answer in one or two sentences.\
        also, kindly provide a brief description of the dataset you are using if you have one."

QUESTION_TWO = "Which prober do you want to use? Please choose from the following options: (1 to 10)"

QUESTION_THREE = "Which development document generated by our agent do you want to use?\
        Please choose from the following options: (1 to 3)"

QUESTION_FOUR = "For iterative improvement, how many iterations do you want to run?\
    please input a positive integer. By default, we will run 3 iterations if you just press enter."

QUESTION_FIVE = "Now agent finished the work, do you want to try another prober or exit? Please answer Y/N"

QUESTION_SIX = "Do you want to use the auto-research feature? The agent will read your probe \
        and annotate train.py with 10 targeted improvement suggestions before iterating. (Y/N, default N)"
